### PR TITLE
added DoctrineExtensions into doc

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by petrparolek** [comment]
@f3l1x

**Comment by f3l1x** [comment]
I think it's to specific to DoctrineExtensions. Just simplify it to common configuration, how to add `customDatetimeFunctions`.

**Comment by f3l1x** [comment]
It's also defined here: https://github.com/nettrine/orm/tree/master/.docs#configuration

**Comment by mabar** [comment]
ping @petrparolek

**Comment by f3l1x** [comment]
Closing for inactivity. Feel free to open it. Thanks anyway.

**Pull request closed without merging**
