### PR TITLE
add phpstorm meta

### PR DESCRIPTION
**Pull request by MartkCz**
```php
$article = $em- >find(\Entities\Article::class);
```

phpstorm suggests methods and properties for variable `$article` from class `Entities\Article`

### CODE REVIEW

**Comment by f3l1x** [comment]
I like it. We use it a lot in projects. Is it possible to don't put it into folder and keep it in the root? I think it is.

**Comment by mabar** [comment]
It is possible. Folder is just for case you have multiple meta files.

Btw, this feature should be primary in [doctrine/orm](https://github.com/doctrine/orm)

**Comment by MartkCz** [comment]
ok, I'll try to send PR to doctrine/orm or create separate repository.

**Comment by mabar** [comment]
Keep it open. We could surely merge it if doctrine team will not.

**Comment by MartkCz** [comment]
https://github.com/doctrine/orm/pull/7676

**Comment by f3l1x** [comment]
It looks like they don't want it in dotrine repo, but I like it. Could you please complete the full list of methods @MartkCz?

**Comment by mabar** [comment]
It's in Doctrine 3.0 milestone 🎉

**Comment by f3l1x** [comment]
I've added some declaration. Thanks @MartkCz.

**Pull request closed without merging**
